---
kind: pipeline
type: docker
name: pipeline

steps:
- name: build
  image: alpine
  commands:
  - echo "docker build"

- name: push
  image: alpine
  commands:
  - echo "docker push"

- name: deploy
  image: alpine
  commands:
  - echo "kubectl apply -f service.yaml"

- name: test
  image: alpine
  commands:
  - echo "npm run autotests"

- name: joba
  image: alpine
  commands:
  - echo "aboba"
